export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_ERROR = "LOGIN_REQUEST_ERROR";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_REQUEST_SUCCESS = "LOGOUT_REQUEST_SUCCESS";
export const LOGOUT_REQUEST_ERROR = "LOGOUT_REQUEST_ERROR";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_REQUEST_SUCCESS = "REGISTER_REQUEST_SUCCESS";
export const REGISTER_REQUEST_ERROR = "REGISTER_REQUEST_ERROR";

export const PRODUCT_GET_REQUEST = "PRODUCT_GET_REQUEST";
export const PRODUCT_GET_REQUEST_SUCCESS = "PRODUCT_GET_REQUEST_SUCCESS";
export const PRODUCT_GET_REQUEST_ERROR = "PRODUCT_GET_REQUEST_ERROR";

export const PRODUCT_ADD_REQUEST = "PRODUCT_ADD_REQUEST";
export const PRODUCT_ADD_REQUEST_SUCCESS = "PRODUCT_ADD_REQUEST_SUCCESS";
export const PRODUCT_ADD_REQUEST_ERROR = "PRODUCT_ADD_REQUEST_ERROR";

export const PRODUCT_REMOVE_REQUEST = "PRODUCT_REMOVE_REQUEST";
export const PRODUCT_REMOVE_REQUEST_SUCCESS = "PRODUCT_REMOVE_REQUEST_SUCCESS";
export const PRODUCT_REMOVE_REQUEST_ERROR = "PRODUCT_REMOVE_REQUEST_ERROR";

export const LOADER_ACTIVATE = "LOADER_ACTIVATE";
export const LOADER_STOP = "LOADER_STOP"; 