export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_ERROR = "LOGIN_REQUEST_ERROR";

export const LOADER_ACTIVATE = "LOADER_ACTIVATE";
export const LOADER_STOP = "LOADER_STOP"; 